package easy;

import java.util.Arrays;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */

public class FindTheDifference_389 {

    public static void main(String[] args) {
        System.out.println();
    }

    public static char findTheDifference(String s, String t) {
        if (t.length() == 1) {
            return t.charAt(0);
        }
        char[] arrayS = s.toCharArray();
        char[] arrayT = t.toCharArray();
        Arrays.sort(arrayS);
        Arrays.sort(arrayT);
        for (int i = 0; i < s.length(); i++) {
            if (arrayS[i] != arrayT[i]) {
                return arrayT[i];
            }
        }
        return arrayT[s.length()];
    }

    // use ascii
    public static char findTheDifference2(String s, String t) {
        int sumS = 0;
        int sumT = 0;
        for (int i = 0; i < s.length(); i++) {
            sumS += s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            sumT += t.charAt(i);
        }
        return (char) (sumT - sumS);
    }
    /**
     * 执行用时 :3 ms, 在所有 Java 提交中击败了56.32%的用户
     * 内存消耗 :35.6 MB, 在所有 Java 提交中击败了82.60%的用户
     */
}
